# Generated by Django 4.2.30 on 2026-06-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (сум)')),
                ('badge', models.CharField(blank=True, choices=[('', 'Нет'), ('new', 'Новинка'), ('hot', 'Хит')], default='', max_length=10, verbose_name='Значок')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('_images', models.TextField(blank=True, db_column='images', default='[]', verbose_name='Фото (JSON)')),
                ('_sizes', models.TextField(blank=True, db_column='sizes', default='[]', verbose_name='Размеры (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
